version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
        sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80"
    volumes:
      - .:/code
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fastapi-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U your_user" ]
        interval: 10s
        timeout: 5s
        retries: 5
    ports:
      - "5442:5432"
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

volumes:
  postgres_data:
